import { NextRequest } from "next/server";

/**
 * This secret is generated by python `secrets.token_urlsafe()`
 * (`secrets` is a built-in module that can be imported directly),
 * and it can be changed in Webhook scope in
 * [App Setting](https://github.com/organizations/GithubBlogBuilder/settings/apps/blogbuilderagent)
 */
const SECRET = "TFdZoGVTWIIoVxHhWW4k7KP7Zi7ROuCukNmMOpzDAqo";

export default function POST(request: NextRequest) {

}